### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Mouvedia** [bbbates/lt-eslint#2]
OS: Mac OS X
version: 0.8.1

```
SyntaxError: Unexpected token /
    at Object.parse (native)
    at read_json_from_file (eval at <anonymous> (file:///Applications/LightTable%200.8.1/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:35236:461), <anonymous>:25:47)
    at find_eslint_config_file (eval at <anonymous> (file:///Applications/LightTable%200.8.1/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:35236:461), <anonymous>:28:50)
    at eslint_config (eval at <anonymous> (file:///Applications/LightTable%200.8.1/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:35236:461), <anonymous>:33:256)
    at lt.object.object_STAR_.call.G__6385__delegate (eval at <anonymous> (file:///Applications/LightTable%200.8.1/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:35236:461), <anonymous>:47:230)
    at lt.object.object_STAR_.call.G__6385 (eval at <anonymous> (file:///Applications/LightTable%200.8.1/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:35236:461), <anonymous>:52:26)
    at cljs.core.apply_to (file:///Applications/LightTable%200.8.1/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6101:88)
    at c (file:///Applications/LightTable%200.8.1/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6194:42)
    at a (file:///Applications/LightTable%200.8.1/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:6236:18)
    at lt.object.handle_redef (file:///Applications/LightTable%200.8.1/LightTable.app/Contents/Resources/app/core/node_modules/lighttable/bootstrap.js:20652:136)
```

If I had to guess Id say you assumed it was a real json file.
cf http://eslint.org/docs/user-guide/configuring#configuration-file-formats

**Comment by bbbates** [comment]
Argh - yeah, you're right. Missed that little snippet:

```
ESLint’s JSON files also allow JavaScript-style comments.
```

Reading a bit closer, it seems that the eslint configuration file rules are a little more complicated than I implemented. I'll push a fix up soon to match as close as possible to the eslint CLI tool, and (add some documentation).

**Comment by bbbates** [comment]
Just a bandaid fix for now - the config file loaded just skips over unparseable json files.

I played around with using the Node.js API directly, which would give access to the built in config load chain, but no dice. Going to need a bit more work to do it properly - will spawn an extra issue.

**Comment by Mouvedia** [comment]
I am gonna try it out again and see if it fixes my problem.

You might be able to leverage https://github.com/json5/json5

**Comment by bbbates** [comment]
You will have to wait until the plugin metadata gets merged into the LT plugin project. 
Alternatively clone this repo into your LT plugin directory and test it out.
